### ISSUE TITLE
ne fonctionne pas avec mon installation x10

### ISSUE THREAD

**Issue by cousarn** [vosmont/Vera-Plugin-ZiBlueGateway#1]
bonjour, j'ai acheté une box vera edge, un module rfplayer, mis à jour les firmwares , pour faire fonctionner mon installation x10. j'ai installé votre module ziblue gateway en suivant le tuto.

les modules x10 sont reconnus en mode discovery mais impossible de réaliser d'apprentissage, ni de créer de module. pour l'instant je suis incapable de me servir de ma box 👎 help !
merci.
tell me if traduction  in english needed
arnaud

**Comment by vosmont** [comment]
Le dernier firmware 1.7.3500 de GetVera a cassé l'API. En utilisant le plugin ALTUI, il sera possible de faire fonctionner correctement le plugin ZiBlue.

**Comment by cousarn** [comment]
Tout à fait. À force d'essayer j'ai fini par réussir en passant par altui...
Merci !

**Comment by vosmont** [comment]
GetVera relancé plusieurs fois. Je suis en attente d'informations sur cette anomalie dans leur API Javascript.

**Comment by cousarn** [comment]
Ok merci!

**Comment by vosmont** [comment]
La version 1.0 devrait corriger le problème.

**Comment by cousarn** [comment]
Ok merci

Provenance : Courrier pour Windows 10

De : vosmont
Envoyé le :mercredi 14 mars 2018 21:45
À : vosmont/Vera-Plugin-ZiBlueGateway
Cc : arnaud; Author
Objet :Re: [vosmont/Vera-Plugin-ZiBlueGateway] ne fonctionne pas avec moninstallation x10 (#1)

La version 1.0 devrait corriger le problème.
