### ISSUE TITLE
Not working with RFPlayer with 1.23 firmware

### ISSUE THREAD

**Issue by davidmartinezcastellanos** [vosmont/Vera-Plugin-ZiBlueGateway#2]
I have just bought the RFPlayer, I have introduced 6 Parrot codes but when I want to add the device it fails, I do not know if I have to use the beta version or the 0.3 one.

**Comment by vosmont** [comment]
Hello,
the last Vera firmware 1.7.3500 has broken the Vera Javascript API.
You can install the plugin ALTUI and you will be able to use the ZiBlue plugin.

**Comment by vosmont** [comment]
The issue should be fixed with the last version 1.0
