### ISSUE TITLE
Erreur en intégration Oregon Rain_meter

### ISSUE THREAD

**Issue by ericzen** [vosmont/Vera-Plugin-ZiBlueGateway#3]
Bonjour,

Mon pluviometre OREGON est bien détecté mais lorsque je clique sur Apprendre, et que je fais OK, j'ai une anomalie Error: [string "--[[..."]:1200: attempt to concatenate local 'name' (a nil value) et l'objet ne se créé pas.

Une idée ?

Cordialement,

**Comment by vosmont** [comment]
Bonjour @ericzen,
désolé je n'avais pas vu votre anomalie.
Effectivement il y a un problème avec le plugin... j'ai oublié le pluviomètre.

Avez-vous la possibilité de passer en mode debug et de me donner la trame reçue par le plugin ?

Cela ressemble à ça : 
`2018-10-11 20:52:25.511   luup_log:52: (ZiBlueGateway::Network.receive)              A 33: {"frame":{"header":{"rfLevel":"-63","protocolMeaning":"OREGON","protocol":"5","dataFlag":"0","infoType":"4","cluster":"0","frameType":"0","rfQuality":"10","floorNoise":"-104","frequency":"433920"},"infos":{"adr":"104","id_PHYMeaning":"THGR122/228/238/268,THGN122/123/132","lowBatt":"1","id_PHY":"0x1A2D","channel":"1","measures":[{"value":"+21.6","type":"temperature","unit":"Celsius"},{"value":"61","type":"hygrometry","unit":"%"}],"qualifier":"33","adr_channel":"26625","subType":"0"}}}`

**Comment by vosmont** [comment]
Le problème devrait être corrigé avec la dernière version dans la branche development (1.3.1).
