### ISSUE TITLE
Pb avec Anémometre OREGON

### ISSUE THREAD

**Issue by chrifabrer** [vosmont/Vera-Plugin-ZiBlueGateway#4]
Mon Anémometre Oregon semble être reconnu mais le plugin crée le Container avec des erreurs : 
Command.deferredProcess   Error: [string "--[[..."]:510: attempt to call field 'setWindSpeed' (a nil value)
Command.deferredProcess   Error: [string "--[[..."]:514: attempt to call field 'setWindDirection' (a nil value)

les logs à la création du container : 
`08      10/27/18 13:42:55.317   JobHandler_LuaUPnP::HandleActionRequest device: 60 service: urn:upnp-org:serviceId:ZiBlueGateway1 action: CreateDevices <0x73902520>
08      10/27/18 13:42:55.318   JobHandler_LuaUPnP::HandleActionRequest argument serviceId=urn:upnp-org:serviceId:ZiBlueGateway1 <0x73902520>
50      10/27/18 13:42:55.324   luup_log:60: (ZiBlueGateway::createDevices)                Create devices [{"protocol":"OREGON","equipmentId":41472,"deviceType":"WIND_SENSOR","featureNames":["direction","wind speed"],"settings":["transmitter"]}] <0x77974000>
50      10/27/18 13:42:55.333   luup_log:60: (ZiBlueGateway::createDevices)                Equipment 'OREGON;41472' - Add device 'OREGON;41472;1', type 'WIND_SENSOR', file 'D_WindSensor1.xml' <0x77974000>
50      10/27/18 13:42:55.414   luup_log:60: (ZiBlueGateway::createDevices)                Equipment 'OREGON;41472' - Device #78(OREGON 41472/1) has been created <0x77974000>
02      10/27/18 13:42:55.415   luup_log:60: (ZiBlueGateway::Device.getInfos)              Can not get infos for device type '78' <0x77974000>
50      10/27/18 13:42:55.416   luup_log:60: (ZiBlueGateway::Equipments.add)               Add equipment 'OREGON;41472', features [ "direction", "wind speed" ], device #78, type unknown <0x77974000>`

les logs suivants
`luup_log:60: (ZiBlueGateway::Network.receive)              A 33: { "frame": { "header": { "rfLevel": "-92", "protocolMeaning": "OREGON", "protocol": "5", "dataFlag": "0", "infoType": "6", "cluster": "0", "frameType": "0", "rfQuality": "2", "floorNoise": "-100", "frequency": "433920" }, "infos": { "adr": "162", "id_PHYMeaning": "WGR800", "lowBatt": "0", "id_PHY": "0x1A89", "channel": "0", "measures": [ { "value": "0.0", "type": "wind speed", "unit": "m/s" }, { "value": "315", "type": "direction", "unit": "degree" } ], "qualifier": "48", "adr_channel": "41472", "subType": "0" } } } <0x743b8520>
50      10/27/18 19:03:04.480   luup_log:60: (ZiBlueGateway::Command.protectedProcess)     Device #78 - Do command 'wind speed' with data '{ "value": "0.0", "type": "wind speed", "unit": "m/s" }' <0x75211520>
01      10/27/18 19:03:04.481   luup_log:60: (ZiBlueGateway::Command.deferredProcess)      Error: [string "--[[..."]:509: attempt to call field 'setWindSpeed' (a nil value) <0x75211520>
50      10/27/18 19:03:04.482   luup_log:60: (ZiBlueGateway::UI.showError)                 Display message: Error (see tab) <0x75211520>
06      10/27/18 19:03:04.483   Device_Variable::m_szValue_set device: 60 service: urn:upnp-org:serviceId:ZiBlueGateway1 variable: LastMessage was: New equipment discovered now: <font color="red">Error (see tab)</font> #hooks: 0 upnp: 0 skip: 0 v:(nil)/NONE duplicate:0 <0x75211520>
50      10/27/18 19:03:04.492   luup_log:60: (ZiBlueGateway::Command.protectedProcess)     Device #78 - Do command 'direction' with data '{ "value": "315", "type": "direction", "unit": "degree" }' <0x75211520>
01      10/27/18 19:03:04.493   luup_log:60: (ZiBlueGateway::Command.deferredProcess)      Error: [string "--[[..."]:512: attempt to call field 'setWindDirection' (a nil value) <0x75211520>
50      10/27/18 19:03:04.494   luup_log:60: (ZiBlueGateway::UI.showError)                 Display message: Error (see tab) <0x75211520>`

**Comment by vosmont** [comment]
Le problème devrait être corrigé avec la dernière version dans la branche development (1.3.1).
